// react-web-components/src/App.js
import { useState } from 'react';

import './App.css';

function App() {
  const [name, setName] = useState('');
  return (
    <div className="App">
      <input
        placeholder="Enter your name"
        onChange={(event) => setName(event.target.value)}
        value={name}
      ></input>
      <div className="greeting">Hello {name}!</div>
      {window.showSearchResult ? (
        <search-result name-attribute={name}></search-result>
      ) : null}
    </div>
  );
}

export default App;

// angular-web-components/src/app/app.component.ts
import { Component } from '@angular/core';

declare var showSearchResult: boolean;

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  name: string | undefined;

  //asign the global variable to a component property
  showSearchResult: boolean = showSearchResult;
}

<div class="App">
  <input placeholder="Enter your name" [(ngModel)]="name" />

  <div class="greeting">Hello {{name}}!</div>

  <!-- check the component property value to render or not the feature -->
  <search-result
    *ngIf="showSearchResult"
    [attr.name-attribute]="name"
  ></search-result>
</div>
